### ISSUE TITLE
Documentation - Add a LICENSE

### ISSUE THREAD

**Issue by ewlarson** [jhu-library-applications/catalyst-blacklight#4]
Glad to see this repo is public. We should add a LICENSE file.

Apache 2.0 was added to the JHU GeoBlacklight repo. We could follow suite here:
https://github.com/jhu-sheridan-libraries/geoblacklight/blob/master/LICENSE

**Comment by fackrellj** [comment]
I added the Apache 2.0 from the JHU GeoBlacklight repo
